name: Dependabot CI

on: pull_request

permissions:
  pull-requests: write

jobs:
  pr-validation:
    runs-on:
      - Linux
      - X64
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
      - name: "Install gh cli"
        uses: asdf-vm/actions/install@v1
      - name: "PR validation"
        uses: Talend/github-actions/dependabot-pr-validation@dependabot_pr_validation-v1.0.2
        with:
          github_token: ${{ secrets.GIT_ACTION_TOKEN }}
