# This GitHub action is required to produce an accurate dependency graph, so that dependabot can function correctly.
# Maintained by InfoSec team
name: 'Dependency Submission'
on: 
  push:
    branches: "*"

permissions:
  contents: read

jobs:
  dependency-submission:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: self-hosted
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Get secrets from VaaS for Gradle build
        uses: hashicorp/vault-action@130d1f5f4fe645bb6c83e4225c04d64cfb62de6e # https://github.com/hashicorp/vault-action/releases/tag/v2.5.0
        id: vault
        with:
          url: https://vault-vaas.service.cd.datapwn.com
          role: github-actions-runner-tpsvc
          method: jwt
          path: jwt-github
          exportEnv: false
          secrets: |
            secret/data/common/jenkins nexus-zl-ci-tpsvc-password | NEXUS_PASSWORD ;

      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          dependency-graph: generate-and-submit
    
      - name: Execute Gradle build
        run: ./gradlew build -x check
        env:
          ORG_GRADLE_PROJECT_nexusTpsvcUrl: "https://artifacts-zl.talend.com/nexus/content/repositories/tpsvc"
          ORG_GRADLE_PROJECT_nexusTpsvcUsername: "ci-tpsvc"
          ORG_GRADLE_PROJECT_nexusTpsvcPassword: "${{ steps.vault.outputs.NEXUS_PASSWORD }}"
          ORG_GRADLE_PROJECT_nexusTalendReleasesUrl: "https://artifacts-zl.talend.com/nexus/content/repositories/releases"
          ORG_GRADLE_PROJECT_nexusTalendReleasesUsername: "ci-tpsvc"
          ORG_GRADLE_PROJECT_nexusTalendReleasesPassword: "${{ steps.vault.outputs.NEXUS_PASSWORD }}"
